name: material
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  zeta_flutter:
    path: ../../../Zeta/zeta_flutter

dev_dependencies:
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
