name: presentation
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_svg: ^2.0.5
  go_router: ^8.0.3
  markdown_widget: ^2.2.0
  zds_flutter:
    path: ../zds-flutter
  zeta_flutter:
    path: ../../Zeta/zeta_flutter

dependency_overrides:
  zds_flutter:
    path: ../zds-flutter
  zeta_flutter:
    path: ../../Zeta/zeta_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: lib/assets/IBMPlexMono.ttf
