name: presentation
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  basic:
    path: ./basic
  collection: ^1.17.0
  cupertino:
    path: ./cupertino
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  go_router: ^8.0.3
  material:
    path: ./material
  material_symbols_icons: ^4.2668.0
  zds_flutter:
    path: ../../zds/zds-flutter
  zeta_flutter:
    path: ../../Zeta/zeta_flutter

dependency_overrides:
  intl: ^0.18.1
  zds_flutter:
    path: ../../zds/zds-flutter
  zeta_flutter:
    # git:
    #   url: https://github.com/zebratechnologies/zeta-flutter
    #   ref: feature/color
    path: ../../Zeta/zeta_flutter

dev_dependencies:
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: lib/assets/IBMPlexMono.ttf
    - family: comic
      fonts:
        - asset: lib/assets/comic.ttf
    - family: Arial
      fonts:
        - asset: lib/assets/arial.ttf
