name: presentation
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  all_lint_rules_community: ^0.0.37
  basic:
    path: ./basic
  collection: ^1.17.0
  cupertino:
    path: ./cupertino
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_svg: ^2.0.5
  go_router: ^10.0.0
  material:
    path: ./material
  material_symbols_icons: ^4.2668.0
  shared_preferences: ^2.2.0
  vector_graphics: ^1.1.7
  zds_flutter:
    path: ../../Reflexis/ztmf-ui-component
  zeta_flutter:
    path: ../../Zeta/zeta_flutter

dependency_overrides:
  intl: ^0.18.1
  zeta_flutter:
    # git:
    #   url: https://github.com/zebratechnologies/zeta-flutter
    #   ref: feature/color
    path: ../../Zeta/zeta_flutter

dev_dependencies:
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: lib/assets/IBMPlexMono.ttf
    - family: comic
      fonts:
        - asset: lib/assets/comic.ttf
    - family: Arial
      fonts:
        - asset: lib/assets/arial.ttf
