name: presentation
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  go_router: ^8.0.3
  zeta_flutter:
    path: ../../Zeta/zeta_flutter
    # git:
    #   url: https://github.com/zebratechnologies/zeta-flutter.git
    #   ref: feature/color

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
